// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAReTmpQq6DjQBY7YP-cskVmdqGvdPrGAI',
    appId: '1:470424523035:web:9c0fb6308ca6c39c2343be',
    messagingSenderId: '470424523035',
    projectId: 'app-message-73e90',
    authDomain: 'app-message-73e90.firebaseapp.com',
    storageBucket: 'app-message-73e90.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBqvuCKbtk3j30ip6GZSId591x3VGAR9_M',
    appId: '1:470424523035:android:f24909bb99535ac12343be',
    messagingSenderId: '470424523035',
    projectId: 'app-message-73e90',
    storageBucket: 'app-message-73e90.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAeLM6EdylpxctmEo1J-aVth80u7cCakmE',
    appId: '1:470424523035:ios:20395074e8ec4eb92343be',
    messagingSenderId: '470424523035',
    projectId: 'app-message-73e90',
    storageBucket: 'app-message-73e90.appspot.com',
    iosBundleId: 'com.example.flutterApplication120',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAeLM6EdylpxctmEo1J-aVth80u7cCakmE',
    appId: '1:470424523035:ios:c8512302a2bd93722343be',
    messagingSenderId: '470424523035',
    projectId: 'app-message-73e90',
    storageBucket: 'app-message-73e90.appspot.com',
    iosBundleId: 'com.example.flutterApplication120.RunnerTests',
  );
}
